import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/context/GlobalProvider";
import ValidateRoutes from "@/components/ValidateRoutes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalProvider>
        <ValidateRoutes>
          <body className={inter.className}>{children}</body>
        </ValidateRoutes>
      </GlobalProvider>
    </html>
  );
}
